parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $cookieCategories: '%fn_cookie_consent.categories%'
      $useLogger: '%fn_cookie_consent.use_logger%'
      $httpOnly: '%fn_cookie_consent.http_only%'
      $formAction: '%fn_cookie_consent.form_action%'
      $csrfProtection: '%fn_cookie_consent.csrf_protection%'

  FatalNetwork\CookieConsentBundle\:
    resource: '../../'
    exclude: '../../{vendor}'

  FatalNetwork\CookieConsentBundle\Controller\:
    resource: '../../Controller/*'
    public: true

  FatalNetwork\CookieConsentBundle\Cookie\CookieChecker:
    arguments: ["@=service('request_stack').getCurrentRequest()"]

  FatalNetwork\CookieConsentBundle\Cookie\CookieLogger:
    arguments:
      $request: "@=service('request_stack').getCurrentRequest()"
